spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://localhost:3306/order_db?createDatabaseIfNotExist=true
    username: root
    password: Shannu@sql123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

server:
  port: 8003

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: localhost
    prefer-ip-address: false
    instance-id: order-service:8003

#JWT Configuration

jwt:
  secret: MySecretKeyForJWTTokenGenerationAndValidation2026ECommerceApplication
  expiration: 86400000 #24 hours in milliseconds
